[package]
name = "merger"
version = "0.1.0"
edition = "2021"


[dependencies]
slint = "1.8.0"
polars = {version = "0.44.2", features = ["lazy"]}
rfd = "0.14.1"
csv = "1.3.1"
dirs = "5.0.1"
regex = "1.11.1"


[build-dependencies]
slint-build = "1.8.0"


#![windows_subsystem = "windows"]
