[package]
name = "merger"
<<<<<<< HEAD
version = "0.1.0"
edition = "2021"


[dependencies]
slint = "1.8.0"
polars = {version = "0.44.2", features = ["lazy"]}
=======
version = "1.0.0"
edition = "2021"

[dependencies]
slint = "1.8.0"
polars = { version = "0.44.2", features = ["lazy"] }
>>>>>>> 3e3286f (Updater checker and error handling)
rfd = "0.14.1"
csv = "1.3.1"
dirs = "5.0.1"
regex = "1.11.1"
scraper = "0.17"
serde_json = "1.0"
caseless = "0.2"

<<<<<<< HEAD

[build-dependencies]
slint-build = "1.8.0"


#![windows_subsystem = "windows"]
=======
# depend on the local lib by its package name
update-checker = { package = "update-checker", path = "updateChecker", features = ["slint"] }

[build-dependencies]
winres = "0.1"
slint-build = "1.8.0"

>>>>>>> 3e3286f (Updater checker and error handling)
